import { ProofCard } from '@/types';

export const PROOF_CARDS: ProofCard[] = [
  { id: 'age_over_18', title: 'Age Eligibility', description: 'Prove a minimum age without publishing your birthdate.', icon: '01', color: 'patina', fields: [{ key: 'birthdate', label: 'Date of birth', placeholder: 'YYYY-MM-DD', type: 'date', visibility: 'private', hint: 'Submitted to the proof service, but excluded from public signals.' }] },
  { id: 'accredited_investor', title: 'Accredited Investor', description: 'Prove net worth exceeds a threshold without publishing the amount.', icon: '02', color: 'spectral', fields: [{ key: 'netWorth', label: 'Net worth (USD cents)', placeholder: '100000000', type: 'number', visibility: 'private', hint: 'Example: $1,000,000 = 100000000 cents.' }, { key: 'threshold', label: 'Minimum threshold (USD cents)', placeholder: '100000000', type: 'number', visibility: 'public', hint: 'Public policy parameter. Defaults to $1,000,000.' }] },
  { id: 'credit_score_range', title: 'Credit Score', description: 'Prove a score meets the required range without publishing the exact score.', icon: '03', color: 'patina', fields: [{ key: 'creditScore', label: 'Credit score', placeholder: '750', type: 'number', visibility: 'private', hint: 'Must be between 300 and 850.' }, { key: 'minimumScore', label: 'Minimum required score', placeholder: '650', type: 'number', visibility: 'public', hint: 'Public policy parameter for this claim.' }] },
  { id: 'jurisdiction_check', title: 'Jurisdiction Check', description: 'Prove a country code matches an allowed jurisdiction without publishing your code.', icon: '04', color: 'spectral', fields: [{ key: 'countryCode', label: 'Country code', placeholder: '840', type: 'number', visibility: 'private', hint: 'ISO 3166-1 numeric code. US = 840, GB = 826, NG = 566.' }, { key: 'allowedCountryCode', label: 'Allowed country code', placeholder: '840', type: 'number', visibility: 'public', hint: 'Public policy parameter supplied by the verifier in production.' }] },
  { id: 'source_of_funds', title: 'Source of Funds', description: 'Prove a private history commitment matches a public funds policy.', icon: '05', color: 'patina', fields: [{ key: 'transactionHistoryHash', label: 'Transaction history hash', placeholder: '12345678', type: 'number', visibility: 'private', hint: 'Poseidon hash submitted to the proof service.' }, { key: 'compliancePolicyHash', label: 'Compliance policy hash', placeholder: '87654321', type: 'number', visibility: 'public', hint: 'Public policy parameter supplied by the verifier in production.' }] },
  { id: 'sanctions_check', title: 'Sanctions Check', description: 'Prove a private identity commitment against a public sanctions tree.', icon: '06', color: 'spectral', fields: [{ key: 'identityHash', label: 'Identity hash', placeholder: '99999999', type: 'number', visibility: 'private', hint: 'Poseidon hash submitted to the proof service.' }, { key: 'merkleRoot', label: 'Sanctions Merkle root', placeholder: '0', type: 'number', visibility: 'public', hint: 'Public root supplied by the verifier in production.' }, { key: 'pathNumber', label: 'Path number', placeholder: '0', type: 'number', visibility: 'public', hint: 'Public path derived from identityHash modulo 1024.' }] },
];

export const COLOR_MAP: Record<string, Record<string, string>> = {
  patina: { border: 'border-patina-500/30', hover: 'hover:border-patina-400/70', badge: 'bg-patina-500/15 text-patina-300 border-patina-500/30', button: 'bg-patina-400 hover:bg-patina-300 text-ink-950', icon: 'text-patina-300' },
  spectral: { border: 'border-spectral/25', hover: 'hover:border-spectral/60', badge: 'bg-spectral/10 text-spectral border-spectral/25', button: 'bg-spectral hover:bg-spectral-soft text-ink-950', icon: 'text-spectral' },
};
